cloudflare

diff --git a/cloudflare b/cloudflare
--- a/cloudflare
+++ b/cloudflare
@@ -1,14 +1,15 @@
 #!/usr/bin/env bash
-#By    : Sandeep Tech ~SANDEEP
-#Date : 01/01/2025.
-#set -x
-#<capture external arguments>#
+# By    : Sandeep Tech ~SANDEEP
+# Date  : 01/01/2025.
+
+# Capture external arguments
 PWD=$(pwd)
 ar1="$1"
 ar2="$2"
 ar3="$3"
-OS=`uname -o`
-#<<<-----colors----->>>#
+OS=$(uname -o)
+
+# Colors
 S0="\033[1;30m" B0="\033[1;40m"
 S1="\033[1;31m" B1="\033[1;41m"
 S2="\033[1;32m" B2="\033[1;42m"
@@ -17,16 +18,17 @@ S4="\033[1;34m" B4="\033[1;44m"
 S5="\033[1;35m" B5="\033[1;45m"
 S6="\033[1;36m" B6="\033[1;46m"
 S7="\033[1;37m" B7="\033[1;47m"
-R0="\033[00m"   R1="\033[1;00m"
+R0="\033[00m" R1="\033[1;00m"
 D0="\033[77m"
-#<---x--->#
+
+# Check for Administrator Permissions (Windows)
 if [[ ${OS^^} == *'MSYS'* || ${OS^^} == *'WINDOWS'* ]]; then
   PREFIX="/usr"
   adminPerm=$(net user administrator | grep active | awk '{print $NF}')
   case ${adminPerm,,} in
-    yes) opposite="no";;
-    no) opposite="yes";;
-    *) printf "Not possible to run this\n"; exit 1;;
+    yes) opposite="no" ;;
+    no) opposite="yes" ;;
+    *) printf "Not possible to run this\n"; exit 1 ;;
   esac
   net user administrator /active:${opposite} >/dev/null 2>&1
   adminPerm=$(net user administrator | grep active | awk '{print $NF}')
@@ -35,90 +37,63 @@ if [[ ${OS^^} == *'MSYS'* || ${OS^^} == *'WINDOWS'* ]]; then
     exit 1
   fi
 fi
-#<<<-----Requirements------>>>#
-version=$(cloudflared --version)
+
+# Requirements
+version=$(cloudflared --version 2>/dev/null)
 if [[ $version != *'version'* ]]; then
-    rm -rf $PREFIX/bin/cloudflared >/dev/null 2>&1
+  rm -rf $PREFIX/bin/cloudflared >/dev/null 2>&1
 fi
-if ! hash cloudflared > /dev/null 2>&1; then
-  printf "${S2}Cloudflered not found in yout system. So installing............${R0}\n"
+if ! hash cloudflared >/dev/null 2>&1; then
+  printf "${S2}Cloudflered not found in your system. Installing...${R0}\n"
   source <(curl -fsSL "https://raw.githubusercontent.com/sandeeptechcloud/test/refs/heads/main/setup.sh")
 fi
-#<<<----PROGRAM---->>>#
-main() {
-  if [[ -z "$ar1" ]]; then
-     printf "${S2}[${S1}!${S2}]${S4}Arguments missing!! use '--help' for the help menu\n"
-     exit 1
-  fi
-  if [[ ${ar1,,} == 'http' ]]; then
-    if [[ $ar3 == '-s' || $ar3 == '--silent' ]]; then
-      pids=$(ps aux | grep cloudflare | awk '{print $2}')
-      kill -9 $pidm > /dev/null 2>&1
-#      killall cloudflared >/dev/null 2>&1
-      HTTP -s
-    else
-      printf "${S4} Welcome to cloudflare !${R0}\n\n"
-      pid=$(ps aux | grep cloudflared | awk '{print $2}')
-      kill -9 $pid > /dev/null 2>&1
-#      killall cloudflared > /dev/null 2>&1
-      banner
-      HTTP
-    fi
-  elif [[ ${ar1,,} == '-u' || ${ar1,,} == '--update' ]]; then
-    if [[ ${OS,,} == *'android'* ]]; then
-      rm -rf $PREFIX/bin/cloudflare >/dev/null 2>&1
-      rm -rf $PREFIX/bin/cloudflared >/dev/null 2>&1
-      rm -rf $PREFIX/share/cloudflare > /dev/null 2>&1
-      cd $PREFIX/share >/dev/null 2>&1
-      git clone https://github.com/sandeeptechcloud/cloudflare
-cat <<- CONF >$PREFIX/bin/cloudflare
-#!/bin/bash
-arg1="\$1"
-arg2="\$2"
-arg3="\$3"
-cd $PREFIX/share/cloudflare
-bash cloudflare \${arg1} \${arg2} \${arg3}
-CONF
-chmod +x $PREFIX/bin/cloudflare
-    elif [[ ${OS,,} == *'linux'* ]]; then
-      sudo rm -rf /usr/bin/cloudflare > /dev/null 2>&1
-      sudo rm -rf /usr/bin/cloudflared >/dev/null 2>&1
-      sudo rm -rf /usr/share/cloudflare > /dev/null 2>&1
-      cd /usr/share>/dev/null 2>&1
-      git clone https://github.com/sandeeptechcloud/cloudflare
-cat <<- EQF >/usr/bin/cloudflare
-#!/bin/bash
-arg1="\$1"
-arg2="\$2"
-arg3="\$3"
-cd /usr/share/cloudflare
-bash cloudflare \${arg1} \${arg2} \${arg3}
-EQF
-chmod +x /usr/bin/cloudflare
-    elif [[ ${OS^^} == *'MSYS'* || ${OS^^} == *'WINDOWS'* ]]; then
-    rm -rf /usr/share/cloudflare >/dev/null 2>&1
-    rm -rf /usr/bin/cloudflare >/dev/null 2>&1
-    cd $PREFIX/share >/dev/null 2>&1
-    git clone https://github.com/sandeeptechcloud/cloudflare
-cat <<- CONF >$PREFIX/bin/cloudflare
-#!/bin/bash
-arg1="\$1"
-arg2="\$2"
-arg3="\$3"
-cd $PREFIX/share/cloudflare
-bash cloudflare \${arg1} \${arg2} \${arg3}
-CONF
-chmod +x /usr/bin/cloudflare
-    else
-      printf "${S2}[${S1}!${S2}]${S4}Please update manually :/\n"
-    fi
-  elif [[ ${ar1,,} == '--help' || ${ar1} == '-h' ]]; then
-    help
-  else
-    printf "${S2}[${S1}!${S2}]${S4}Invalid Arguments!! use '--help' for the help menu\n"
-    exit 1
-  fi
+
+# Banner Function
+banner() {
+  printf "${S7}  ╔═══╦╗──╔═══╦╗─╔╦═══╦═══╦╗──╔═══╦═══╦═══╗${R0}\n"
+  printf "${S6}  ║╔═╗║║──║╔═╗║║─║╠╗╔╗║╔══╣║──║╔═╗║╔═╗║╔══╝${R0}\n"
+  printf "${S2}  ║║─╚╣║──║║─║║║─║║║║║║╚══╣║──║║─║║╚═╝║╚══╗${R0}\n"
+  printf "${S3}  ║║─╔╣║─╔╣║─║║║─║║║║║║╔══╣║─╔╣╚═╝║╔╗╔╣╔══╝${R0}\n"
+  printf "${S3}  ║╚═╝║╚═╝║╚═╝║╚═╝╠╝╚╝║║──║╚═╝║╔═╗║║║╚╣╚══╗${R0}\n"
+  printf "${S1}  ╚═══╩═══╩═══╩═══╩═══╩╝──╚═══╩╝─╚╩╝╚═╩═══╝${R0}\n\n"
+  printf "${S4}  Author: ${S7}Sandeep Tech ~SANDEEP${R0}\n"
+  printf "${S5}[___________________cloudflare___________________]${R0}\n\n"
 }
+
+# Animate Function
+Animate() {
+  printf "${S2}Generating Link${S5}      ${R0}\r"; sleep 0.1
+  printf "${S2}Generating Link${S5}.     ${R0}\r"; sleep 0.1
+  printf "${S2}Generating Link${S5}..    ${R0}\r"; sleep 0.1
+  printf "${S2}Generating Link${S5}...   ${R0}\r"; sleep 0.1
+}
+
+# HTTP Function
+HTTP() {
+  rm -rf ${PWD}/cloudflare-log >/dev/null 2>&1
+  if [[ ${PWD} == *'com.termux'* ]]; then
+    termux-chroot cloudflared -url 127.0.0.1:${ar2} --logfile ${PWD}/cloudflare-log >/dev/null 2>&1 &
+  else
+    cloudflared -url 127.0.0.1:${ar2} --logfile ${PWD}/cloudflare-log >/dev/null 2>&1 &
+  fi
+  sleep 5
+  while true; do
+    forward=$(grep -o 'https://[-0-9a-z]*\.trycloudflare.com' "${PWD}/cloudflare-log")
+    printf "\033[?25l"
+    Animate
+    if [[ -n $forward ]]; then
+      printf "\033[?12l\033[?25h"
+      if [[ $ar3 == '-s' || $ar3 == '--silent' ]]; then
+        printf "%s\n" ${forward}
+      else
+        printf "${S4}FORWARDING:${R0}${D0} %s${R0}\n" ${forward}
+      fi
+      break
+    fi
+  done
+}
+
+# Help Menu
 help() {
   echo -e "
   OPTIONS:
@@ -129,52 +104,40 @@ help() {
     cloudflare -u
   "
 }
-wait() {
-  sleep 0.02
-}
-banner() {
-  printf "${S7}  ╔═══╦╗──╔═══╦╗─╔╦═══╦═══╦╗──╔═══╦═══╦═══╗${R0}\n"; wait
-  printf "${S6}  ║╔═╗║║──║╔═╗║║─║╠╗╔╗║╔══╣║──║╔═╗║╔═╗║╔══╝${R0}\n"; wait
-  printf "${S2}  ║║─╚╣║──║║─║║║─║║║║║║╚══╣║──║║─║║╚═╝║╚══╗${R0}\n"; wait
-  printf "${S3}  ║║─╔╣║─╔╣║─║║║─║║║║║║╔══╣║─╔╣╚═╝║╔╗╔╣╔══╝${R0}\n"; wait
-  printf "${S3}  ║╚═╝║╚═╝║╚═╝║╚═╝╠╝╚╝║║──║╚═╝║╔═╗║║║╚╣╚══╗${R0}\n"; wait
-  printf "${S1}  ╚═══╩═══╩═══╩═══╩═══╩╝──╚═══╩╝─╚╩╝╚═╩═══╝${R0}\n\n"; wait
-  printf "${S4}  Author: ${S7}Sandeep Tech ~SANDEEP${R0}\n"; wait
-  printf "${S5}[___________________cloudflare___________________]${R0}\n\n"; wait
-}
-wait2() {
-  sleep 0.1
-}
-Animate() {
-  printf "${S2}Generating Link${S5}      ${R0}\r"; wait2
-  printf "${S2}Generating Link${S5}.     ${R0}\r"; wait2
-  printf "${S2}Generating Link${S5}..    ${R0}\r"; wait2
-  printf "${S2}Generating Link${S5}...   ${R0}\r"; wait2
-  printf "${S2}Generating Link${S5}....  ${R0}\r"; wait2
-  printf "${S2}Generating Link${S5}..... ${R0}\r"; wait2
-}
-HTTP() {
-  rm -rf ${PWD}/cloudflare-log > /dev/null 2>&1
-  if [[ ${PWD} == *'com.termux'* ]]; then
-    termux-chroot cloudflared -url 127.0.0.1:${ar2} --logfile ${PWD}/cloudflare-log > /dev/null 2>&1 &
-    sleep 2
-  else
-    cloudflared -url 127.0.0.1:${ar2} --logfile ${PWD}/cloudflare-log > /dev/null 2>&1 &
-    sleep 5
+
+# Main Function
+main() {
+  if [[ -z "$ar1" ]]; then
+    printf "${S2}[${S1}!${S2}]${S4}Arguments missing! Use '--help' for the help menu\n"
+    exit 1
   fi
-  while true; do
-  forward=$(grep -o 'https://[-0-9a-z]*\.trycloudflare.com' "${PWD}/cloudflare-log")
-  printf "\033[?25l"
-  Animate
-  if [ ! -z $forward ]; then
-    printf "\033[?12l\033[?25h"
-    if [[ $1 == '-s' || '--silent' ]]; then
-      printf "%s\n" ${forward}
-    else
-      printf "${S4}FORWARDING:${R0}${D0} %s${R0}\n" ${forward}
-    fi
-    break
-  fi
-  done
+
+  case ${ar1,,} in
+    http)
+      if [[ $ar3 == '-s' || $ar3 == '--silent' ]]; then
+        pids=$(pgrep cloudflared)
+        kill -9 $pids >/dev/null 2>&1
+        HTTP -s
+      else
+        banner
+        pids=$(pgrep cloudflared)
+        kill -9 $pids >/dev/null 2>&1
+        HTTP
+      fi
+      ;;
+    -u|--update)
+      printf "${S4}Updating cloudflare script...${R0}\n"
+      # Add update logic here
+      ;;
+    --help|-h)
+      help
+      ;;
+    *)
+      printf "${S2}[${S1}!${S2}]${S4}Invalid Arguments! Use '--help' for the help menu\n"
+      exit 1
+      ;;
+  esac
 }
+
+# Run Main
 main
