Update cloudflare

diff --git a/cloudflare b/cloudflare
--- a/cloudflare
+++ b/cloudflare
@@ -1,3 +1,180 @@
-z="
-";bBz='user';MFz='k '\''{';Fz='ar2=';dBz='inis';HKz=''\''* ]';SHz='e>/d';wIz='╚══╗';lBz='{pri';LLz='rd ]';aIz=' {';tBz=',,} ';BLz='*\.t';yDz='(cur';RBz='S'\''* ';AFz='s'\'' |';kHz='leas';PHz='cd /';gLz='done';sCz='comm';DLz=''\'' "$';MCz='to r';pIz='╔══╣';Ez='"$1"';xCz='ell ';ZIz='er()';uGz=' \${';Xz='1m"';jBz=' | a';pz='6m" ';XKz=' &';IJz='╝─╚╩';cFz='pid=';GCz='*) p';lz='5m" ';yCz='in A';nCz='}[${';bGz='d/cl';aFz='!${R';YBz='nPer';LIz='E:';yEz='= '\''-';UJz='NDEE';cIz='}  ╔';hJz='{';mFz='null';HGz='e >/';BCz='no) ';vKz='o '\''h';ZKz='-url';YHz=' /us';gDz='}Clo';OFz='}'\'')';cJz='are_';KCz='ossi';qEz=',} =';EJz='${S1';YFz='lcom';FDz=' 1';sBz='Perm';AIz=' -e ';NEz='chcl';nEz=' men';qHz=''\''--h';WLz='" ${';rz='6m"';YDz='loud';PDz='ersi';THz='EQF ';TFz='HTTP';Zz='2m" ';OBz=' == ';kCz='prin';BBz='[1;0';rGz='bash';bEz='S4}A';kGz='="\$';JJz='╝╚═╩';YCz='/dev';QKz=':${a';UDz='rm -';FKz='m.te';KGz='/clo';TLz='ilen';iCz='; th';TJz=' ~SA';NIz='ttp ';aLz='ING:';hHz='bin/';UBz='PREF';PKz='.0.1';PJz='{S7}';BFz='| $a';XFz='} We';dz='3m" ';vFz=''\''-u'\''';sGz='\${a';kDz=' fou';LFz='| aw';sz='S7="';SKz='--lo';oFz='1';TBz='then';wBz=' opp';sJz=' wai';HBz='OS^^';ABz='R1="';CIz='ONS:';nBz='NF}'\''';XEz='() {';gCz='ite}';sEz='ttp'\''';uBz='in';Rz='B0="';ZFz='e to';Dz='ar1=';oDz='yste';lGz='1"';BEz='sSL ';hz='4m" ';GIz='  To';wJz='}...';BIz='OPTI';CFz='-sil';ICz='f "N';JLz='z $f';GDz='fi';aKz=' 127';QCz='exit';DIz='-s -';Wz='B1="';cLz='0} %';XGz='.com';oCz='S1}!';WHz='e/cl';FIz='    ';KKz='hroo';dIz='═══╦';bJz='_clo';SFz='m > ';vGz='} \$';YJz='${S5';jJz='ate(';rKz='forw';hFz='clou';wKz='ttps';tJz='t2';eGz='CONF';SIz='TE:';hKz='${PW';BDz='ator';MGz='ev/n';AHz='d +x';kFz=' > /';AEz='l -f';tKz='$(gr';yGz='chmo';fEz='sing';EFz='pids';gz='S4="';eJz='{R0}';tGz='rg1}';XIz='p 0.';YIz='02';NKz='rl 1';dFz='$(ps';tDz='....';eHz='WIND';Uz='S1="';oGz='arg3';GEz='hubu';eKz='} --';FFz='=$(p';LGz='> /d';xz='[00m';wGz='{arg';OLz='3[?2';UHz='>/us';PEz='test';mCz='${S2';KFz='are ';tz='7m" ';TCz='or /';LKz='t cl';CHz='EFIX';HDz='vers';IFz='grep';oIz='╗╔╗║';DGz='OS,,';LBz='* ||';mHz='date';ZLz='WARD';sHz='1} =';wFz=' || ';jFz='red ';FJz='}  ╚';HEz='serc';aHz=''\''MSY';GKz='rmux';eEz=' mis';Qz='0m" ';IBz='} ==';KHz='-rf ';wHz='id A';QDz='on !';ZEz=' "$a';XDz='in/c';GLz='l"';qz='B6="';yKz='-0-9';JFz=' clo';HIz=' ign';rFz='elif';Vz='1m" ';OEz='oud/';qJz='   $';Jz='OS=`';WKz='log ';vIz='╚═╝║';dKz='{ar2';UKz='e ${';nGz='2"';gIz='═══╗';TGz='e ht';lIz='╔═╗║';TIz='re -';YLz='}FOR';SGz='clon';MKz='d -u';MEz='epte';QJz='Sand';Sz='[1;4';OIz='<por';OHz='e > ';jGz='arg1';oEz='u\n"';fLz='k';IKz='term';fBz='or |';rHz='elp'\''';qCz='S4}R';iBz='tive';ACz='o";;';NCz='un t';JGz='hare';VIz='wait';kIz='}  ║';IHz='sudo';pBz='case';mEz='help';CLz='rycl';RCz=' 1;;';SBz=']]; ';ADz='istr';MHz='/sha';sFz=' [[ ';GBz='[ ${';rBz='dmin';Bz='$(pw';Lz='e -o';xIz='${S3';tHz='h'\'' ]';uJz='}.  ';yz='"   ';kz='S5="';LEz='ande';TEz='main';Gz='"$2"';PCz='n"; ';ZHz='^^} ';mz='B5="';cGz='cat ';NDz='ion)';REz='s/he';wCz='r sh';nz='5m"';lJz='}Gen';xEz='r3 =';CKz='-log';aEz='r1" ';SLz=''\''--s';bFz='\n"';RGz='git ';VFz='else';RFz='$pid';XHz='EQF';hCz='" ]]';rIz='║─╚╣';WJz='"; w';RLz=''\''-s'\''';RDz='= *'\''';EGz=' *'\''a';DBz='[77m';oz='S6="';HLz='ate';XJz='ait';gGz='REFI';uEz=' the';pHz='y :/';CGz='hen';GGz='id'\''*';QGz=' >/d';VHz='r/bi';ZBz='m=$(';uHz='S4}I';NBz='S^^}';JEz='nt.c';FLz='[?25';cCz='m,,}';dDz='h cl';jCz='en';WGz='thub';gKz='ile ';JBz=' *'\''M';Mz='`';az='B2="';uKz='ep -';YEz='[ -z';lHz='e up';MJz='}  A';pCz='}]${';iGz='n/cl';dGz='<<- ';aCz='l 2>';ALz='a-z]';FCz='s";;';RHz='shar';RJz='eep ';BGz=']; t';DCz='site';ZDz='flar';Iz='"$3"';Oz='\033';JKz='ux-c';yIz='║─╔╣';ZGz='deep';WEz='h")';vDz='}\n"';IGz='IX/s';fIz='╗─╔╦';rJz='\r";';xJz='.  $';vBz='yes)';VGz='//gi';CBz='D0="';VBz='IX="';cEz='rgum';SEz='ads/';FHz='== *';FEz='.git';bKz='.0.0';uCz='prom';vz='7m"';kBz='wk '\''';kJz=') {';qKz='do';iFz='dfla';mGz='arg2';uIz='╚══╣';WCz='{opp';hGz='X/bi';OGz='2>&1';PLz='5h"';gBz=' gre';pDz='m. S';NFz='t $2';UFz=' -s';wz='R0="';WIz='slee';hBz='p ac';Yz='S2="';tIz='║║║║';iHz='re >';dLz='s${R';yJz='.. $';jDz=' not';BKz='}/cl';pGz='3"';oBz=')';LCz='ble ';wEz='[ $a';rDz='stal';XCz='e} >';UCz='acti';aBz='net ';QIz='ON]';dCz=' != ';nDz='ut s';BHz=' $PR';qGz='are';bDz='if !';WFz='${S4';eLz='brea';VDz='rf $';TKz='gfil';fHz='OWS'\''';AGz='e'\'' ]';wDz='sour';YKz='p 2';HCz='rint';qIz='╔══╝';CDz=' mod';GJz='═══╩';iIz='it';RIz='UPDA';tCz='and ';DFz='ent'\''';dJz='__]$';sKz='ard=';CEz='"htt';tFz='${ar';Tz='0m"';qBz=' ${a';XBz='admi';EHz='${OS';qFz='er';JCz='ot p';LDz='lare';nJz='ing ';QHz='usr/';OJz='r: $';JHz=' rm ';iz='B4="';MBz=' ${O';pFz='bann';hDz='udfl';eCz='"${o';kEz='for ';UEz='/set';lEz='the ';cKz='.1:$';gEz='!! u';fFz=' | g';uFz='1,,}';MIz='re h';tEz=' ]];';UGz='tps:';lKz='&1 &';DEz='ps:/';pKz='ue; ';KEz='om/s';lFz='dev/';IDz='ion=';SJz='Tech';VCz='ve:$';EBz='"';KBz='SYS'\''';ULz='t'\'' ]';RKz='r2} ';ZCz='/nul';cHz='{OS^';EKz='*'\''co';dHz='^} =';AJz='╔╗╔╣';lDz='nd i';xDz='ce <';GFz='s au';cDz=' has';PFz='kill';aJz='____';DJz='║║╚╣';oKz='e tr';eBz='trat';mJz='erat';KDz='oudf';BJz='╚═╝╠';HHz='ux'\''*';NLz='l\03';FGz='ndro';DHz='/bin';lCz='tf "';vJz='}.. ';oJz='Link';fz='3m"';Nz='S0="';iJz='Anim';Hz='ar3=';nFz=' 2>&';uz='B7="';eIz='╗──╔';fDz='&1; ';ECz='="ye';jEz='lp'\'' ';aDz='ed >';SDz='ion'\''';gHz='rf /';bCz='&1';AKz='{PWD';WDz='IX/b';VJz='P${R';mBz='nt $';qDz='o in';LHz='ared';iKz='D}/c';mIz='║──║';NHz='re/c';CJz='╝╚╝║';KLz='orwa';VKz='are-';QEz='/ref';fCz='ppos';PIz='t> [';MDz='d --';bz='2m"';sIz='║─║║';JIz='er.';fKz='logf';Pz='[1;3';mDz='n yo';yHz='echo';ELz='")';QLz='[ $1';yBz='e="n';VEz='up.s';NJz='utho';fJz='\n\n';JDz='$(cl';IEz='onte';ODz='[ $v';uDz='${R0';dEz='ents';bHz='|| $';EEz='/raw';iDz='ered';IIz='ore ';YGz='/san';nHz=' man';UIz='u';hIz='; wa';OCz='his\';oHz='uall';cBz=' adm';pEz='ar1,';KJz='═══╝';vEz='n';cz='S3="';gFz='rep ';Az='PWD=';PGz='cd $';nIz='║─║╠';mKz='p 5';vCz='pt o';hEz='se '\''';ILz=' ! -';bIz='${S7';gJz='2() ';nKz='whil';GHz=''\''lin';xHz='}';pJz='}   ';vHz='nval';DKz='PWD}';FBz='if [';QBz='NDOW';jHz='S4}P';eFz=' aux';EDz='0}\n';XLz='ard}';xGz='3}';xKz='://[';aGz='tech';CCz='oppo';SCz='esac';DDz='e${R';OKz='27.0';ez='B3="';HFz='x | ';rEz='= '\''h';HJz='╝──╚';PBz='*'\''WI';LJz='}\n\';bLz='}${D';rCz='his ';xFz=''\''--u';kKz='g > ';fGz=' >$P';jIz='${S6';MLz='[?12';VLz='%s\n';sDz='ling';TDz='* ]]';ZJz='}[__';EIz='ent ';Cz='d)';Kz='unam';jz='4m"';xBz='osit';KIz='USAG';jKz='e-lo';WBz='/usr';QFz=' -9 ';yFz='pdat';eDz='d > ';iEz='--he';NGz='ull ';
-eval "$Az$Bz$Cz$z$Dz$Ez$z$Fz$Gz$z$Hz$Iz$z$Jz$Kz$Lz$Mz$z$Nz$Oz$Pz$Qz$Rz$Oz$Sz$Tz$z$Uz$Oz$Pz$Vz$Wz$Oz$Sz$Xz$z$Yz$Oz$Pz$Zz$az$Oz$Sz$bz$z$cz$Oz$Pz$dz$ez$Oz$Sz$fz$z$gz$Oz$Pz$hz$iz$Oz$Sz$jz$z$kz$Oz$Pz$lz$mz$Oz$Sz$nz$z$oz$Oz$Pz$pz$qz$Oz$Sz$rz$z$sz$Oz$Pz$tz$uz$Oz$Sz$vz$z$wz$Oz$xz$yz$ABz$Oz$BBz$Tz$z$CBz$Oz$DBz$EBz$z$FBz$GBz$HBz$IBz$JBz$KBz$LBz$MBz$NBz$OBz$PBz$QBz$RBz$SBz$TBz$z$UBz$VBz$WBz$EBz$z$XBz$YBz$ZBz$aBz$bBz$cBz$dBz$eBz$fBz$gBz$hBz$iBz$jBz$kBz$lBz$mBz$nBz$oBz$z$pBz$qBz$rBz$sBz$tBz$uBz$z$vBz$wBz$xBz$yBz$ACz$z$BCz$CCz$DCz$ECz$FCz$z$GCz$HCz$ICz$JCz$KCz$LCz$MCz$NCz$OCz$PCz$QCz$RCz$z$SCz$z$aBz$bBz$cBz$dBz$eBz$TCz$UCz$VCz$WCz$xBz$XCz$YCz$ZCz$aCz$bCz$z$XBz$YBz$ZBz$aBz$bBz$cBz$dBz$eBz$fBz$gBz$hBz$iBz$jBz$kBz$lBz$mBz$nBz$oBz$z$FBz$GBz$XBz$YBz$cCz$dCz$eCz$fCz$gCz$hCz$iCz$jCz$z$kCz$lCz$mCz$nCz$oCz$mCz$pCz$qCz$NCz$rCz$sCz$tCz$uCz$vCz$wCz$xCz$yCz$rBz$ADz$BDz$CDz$DDz$EDz$EBz$z$QCz$FDz$z$GDz$z$GDz$z$HDz$IDz$JDz$KDz$LDz$MDz$HDz$NDz$z$FBz$ODz$PDz$QDz$RDz$HDz$SDz$TDz$iCz$jCz$z$UDz$VDz$UBz$WDz$XDz$YDz$ZDz$aDz$YCz$ZCz$aCz$bCz$z$GDz$z$bDz$cDz$dDz$KDz$LDz$eDz$YCz$ZCz$aCz$fDz$TBz$z$kCz$lCz$mCz$gDz$hDz$iDz$jDz$kDz$lDz$mDz$nDz$oDz$pDz$qDz$rDz$sDz$tDz$tDz$tDz$uDz$vDz$z$wDz$xDz$yDz$AEz$BEz$CEz$DEz$EEz$FEz$GEz$HEz$IEz$JEz$KEz$LEz$MEz$NEz$OEz$PEz$QEz$REz$SEz$TEz$UEz$VEz$WEz$z$GDz$z$TEz$XEz$z$FBz$YEz$ZEz$aEz$SBz$TBz$z$kCz$lCz$mCz$nCz$oCz$mCz$pCz$bEz$cEz$dEz$eEz$fEz$gEz$hEz$iEz$jEz$kEz$lEz$mEz$nEz$oEz$z$QCz$FDz$z$GDz$z$FBz$GBz$pEz$qEz$rEz$sEz$tEz$uEz$vEz$z$FBz$wEz$xEz$yEz$AFz$BFz$xEz$yEz$CFz$DFz$tEz$uEz$vEz$z$EFz$FFz$GFz$HFz$IFz$JFz$hDz$KFz$LFz$MFz$kCz$NFz$OFz$z$PFz$QFz$RFz$SFz$YCz$ZCz$aCz$bCz$z$TFz$UFz$z$VFz$z$kCz$lCz$WFz$XFz$YFz$ZFz$JFz$hDz$KFz$aFz$EDz$bFz$z$cFz$dFz$eFz$fFz$gFz$hFz$iFz$jFz$LFz$MFz$kCz$NFz$OFz$z$PFz$QFz$RFz$kFz$lFz$mFz$nFz$oFz$z$pFz$qFz$z$TFz$z$GDz$z$rFz$sFz$tFz$uFz$OBz$vFz$wFz$tFz$uFz$OBz$xFz$yFz$AGz$BGz$CGz$z$FBz$GBz$DGz$IBz$EGz$FGz$GGz$tEz$uEz$vEz$z$UDz$VDz$UBz$WDz$XDz$YDz$ZDz$HGz$lFz$mFz$nFz$oFz$z$UDz$VDz$UBz$WDz$XDz$YDz$ZDz$aDz$YCz$ZCz$aCz$bCz$z$UDz$VDz$UBz$IGz$JGz$KGz$hDz$KFz$LGz$MGz$NGz$OGz$z$PGz$UBz$IGz$JGz$QGz$MGz$NGz$OGz$z$RGz$SGz$TGz$UGz$VGz$WGz$XGz$YGz$ZGz$aGz$hFz$bGz$KDz$LDz$z$cGz$dGz$eGz$fGz$gGz$hGz$iGz$KDz$LDz$z$jGz$kGz$lGz$z$mGz$kGz$nGz$z$oGz$kGz$pGz$z$PGz$UBz$IGz$JGz$KGz$hDz$qGz$z$rGz$JFz$hDz$KFz$sGz$tGz$uGz$mGz$vGz$wGz$xGz$z$eGz$z$yGz$AHz$BHz$CHz$DHz$KGz$hDz$qGz$z$rFz$sFz$EHz$tBz$FHz$GHz$HHz$tEz$uEz$vEz$z$IHz$JHz$KHz$WBz$DHz$KGz$hDz$KFz$LGz$MGz$NGz$OGz$z$IHz$JHz$KHz$WBz$DHz$KGz$hDz$LHz$QGz$MGz$NGz$OGz$z$IHz$JHz$KHz$WBz$MHz$NHz$YDz$ZDz$OHz$YCz$ZCz$aCz$bCz$z$PHz$QHz$RHz$SHz$MGz$NGz$OGz$z$RGz$SGz$TGz$UGz$VGz$WGz$XGz$YGz$ZGz$aGz$hFz$bGz$KDz$LDz$z$cGz$dGz$THz$UHz$VHz$iGz$KDz$LDz$z$jGz$kGz$lGz$z$mGz$kGz$nGz$z$oGz$kGz$pGz$z$PHz$QHz$RHz$WHz$KDz$LDz$z$rGz$JFz$hDz$KFz$sGz$tGz$uGz$mGz$vGz$wGz$xGz$z$XHz$z$yGz$AHz$YHz$VHz$iGz$KDz$LDz$z$rFz$sFz$EHz$ZHz$FHz$aHz$RBz$bHz$cHz$dHz$RDz$eHz$fHz$TDz$iCz$jCz$z$UDz$gHz$QHz$RHz$WHz$KDz$LDz$QGz$MGz$NGz$OGz$z$UDz$gHz$QHz$hHz$hFz$iFz$iHz$YCz$ZCz$aCz$bCz$z$PGz$UBz$IGz$JGz$QGz$MGz$NGz$OGz$z$RGz$SGz$TGz$UGz$VGz$WGz$XGz$YGz$ZGz$aGz$hFz$bGz$KDz$LDz$z$cGz$dGz$eGz$fGz$gGz$hGz$iGz$KDz$LDz$z$jGz$kGz$lGz$z$mGz$kGz$nGz$z$oGz$kGz$pGz$z$PGz$UBz$IGz$JGz$KGz$hDz$qGz$z$rGz$JFz$hDz$KFz$sGz$tGz$uGz$mGz$vGz$wGz$xGz$z$eGz$z$yGz$AHz$YHz$VHz$iGz$KDz$LDz$z$VFz$z$kCz$lCz$mCz$nCz$oCz$mCz$pCz$jHz$kHz$lHz$mHz$nHz$oHz$pHz$bFz$z$GDz$z$rFz$sFz$tFz$uFz$OBz$qHz$rHz$wFz$tFz$sHz$yEz$tHz$BGz$CGz$z$mEz$z$VFz$z$kCz$lCz$mCz$nCz$oCz$mCz$pCz$uHz$vHz$wHz$cEz$dEz$gEz$hEz$iEz$jEz$kEz$lEz$mEz$nEz$oEz$z$QCz$FDz$z$GDz$z$xHz$z$mEz$XEz$z$yHz$AIz$EBz$z$BIz$CIz$z$DIz$CFz$EIz$FIz$FIz$GIz$HIz$IIz$pFz$JIz$z$KIz$LIz$z$hFz$iFz$MIz$NIz$OIz$PIz$BIz$QIz$z$RIz$SIz$z$hFz$iFz$TIz$UIz$z$EBz$z$xHz$z$VIz$XEz$z$WIz$XIz$YIz$z$xHz$z$pFz$ZIz$aIz$z$kCz$lCz$bIz$cIz$dIz$eIz$dIz$fIz$dIz$dIz$eIz$dIz$dIz$gIz$uDz$vDz$hIz$iIz$z$kCz$lCz$jIz$kIz$lIz$mIz$lIz$nIz$oIz$pIz$mIz$lIz$lIz$qIz$uDz$vDz$hIz$iIz$z$kCz$lCz$mCz$kIz$rIz$mIz$sIz$sIz$tIz$uIz$mIz$sIz$vIz$wIz$uDz$vDz$hIz$iIz$z$kCz$lCz$xIz$kIz$yIz$yIz$sIz$sIz$tIz$pIz$yIz$vIz$AJz$qIz$uDz$vDz$hIz$iIz$z$kCz$lCz$xIz$kIz$vIz$vIz$vIz$BJz$CJz$mIz$vIz$lIz$DJz$wIz$uDz$vDz$hIz$iIz$z$kCz$lCz$EJz$FJz$GJz$GJz$GJz$GJz$GJz$HJz$GJz$IJz$JJz$KJz$uDz$LJz$PCz$VIz$z$kCz$lCz$WFz$MJz$NJz$OJz$PJz$QJz$RJz$SJz$TJz$UJz$VJz$EDz$WJz$XJz$z$kCz$lCz$YJz$ZJz$aJz$aJz$aJz$aJz$bJz$hDz$cJz$aJz$aJz$aJz$aJz$dJz$eJz$fJz$WJz$XJz$z$xHz$z$VIz$gJz$hJz$z$WIz$XIz$oFz$z$xHz$z$iJz$jJz$kJz$z$kCz$lCz$mCz$lJz$mJz$nJz$oJz$YJz$pJz$qJz$eJz$rJz$sJz$tJz$z$kCz$lCz$mCz$lJz$mJz$nJz$oJz$YJz$uJz$qJz$eJz$rJz$sJz$tJz$z$kCz$lCz$mCz$lJz$mJz$nJz$oJz$YJz$vJz$qJz$eJz$rJz$sJz$tJz$z$kCz$lCz$mCz$lJz$mJz$nJz$oJz$YJz$wJz$qJz$eJz$rJz$sJz$tJz$z$kCz$lCz$mCz$lJz$mJz$nJz$oJz$YJz$wJz$xJz$eJz$rJz$sJz$tJz$z$kCz$lCz$mCz$lJz$mJz$nJz$oJz$YJz$wJz$yJz$eJz$rJz$sJz$tJz$z$xHz$z$TFz$XEz$z$UDz$VDz$AKz$BKz$KDz$LDz$CKz$kFz$lFz$mFz$nFz$oFz$z$FBz$GBz$DKz$OBz$EKz$FKz$GKz$HKz$BGz$CGz$z$IKz$JKz$KKz$LKz$KDz$LDz$MKz$NKz$OKz$PKz$QKz$RKz$SKz$TKz$UKz$DKz$KGz$hDz$VKz$WKz$LGz$MGz$NGz$OGz$XKz$z$WIz$YKz$z$VFz$z$hFz$iFz$jFz$ZKz$aKz$bKz$cKz$dKz$eKz$fKz$gKz$hKz$iKz$YDz$ZDz$jKz$kKz$YCz$ZCz$aCz$lKz$z$WIz$mKz$z$GDz$z$nKz$oKz$pKz$qKz$z$rKz$sKz$tKz$uKz$vKz$wKz$xKz$yKz$ALz$BLz$CLz$KDz$LDz$XGz$DLz$AKz$BKz$KDz$LDz$CKz$ELz$z$kCz$lCz$Oz$FLz$GLz$z$iJz$HLz$z$FBz$ILz$JLz$KLz$LLz$iCz$jCz$z$kCz$lCz$Oz$MLz$NLz$OLz$PLz$z$FBz$QLz$OBz$RLz$wFz$SLz$TLz$ULz$BGz$CGz$z$kCz$lCz$VLz$WLz$rKz$XLz$z$VFz$z$kCz$lCz$WFz$YLz$ZLz$aLz$uDz$bLz$cLz$dLz$EDz$WLz$rKz$XLz$z$GDz$z$eLz$fLz$z$GDz$z$gLz$z$xHz$z$TEz"
+#!/usr/bin/env bash
+#By    : suman kumar ~BHUTUU
+#Date : 14/11/2021.
+#set -x
+#<capture external arguments>#
+PWD=$(pwd)
+ar1="$1"
+ar2="$2"
+ar3="$3"
+OS=`uname -o`
+#<<<-----colors----->>>#
+S0="\033[1;30m" B0="\033[1;40m"
+S1="\033[1;31m" B1="\033[1;41m"
+S2="\033[1;32m" B2="\033[1;42m"
+S3="\033[1;33m" B3="\033[1;43m"
+S4="\033[1;34m" B4="\033[1;44m"
+S5="\033[1;35m" B5="\033[1;45m"
+S6="\033[1;36m" B6="\033[1;46m"
+S7="\033[1;37m" B7="\033[1;47m"
+R0="\033[00m"   R1="\033[1;00m"
+D0="\033[77m"
+#<---x--->#
+if [[ ${OS^^} == *'MSYS'* || ${OS^^} == *'WINDOWS'* ]]; then
+  PREFIX="/usr"
+  adminPerm=$(net user administrator | grep active | awk '{print $NF}')
+  case ${adminPerm,,} in
+    yes) opposite="no";;
+    no) opposite="yes";;
+    *) printf "Not possible to run this\n"; exit 1;;
+  esac
+  net user administrator /active:${opposite} >/dev/null 2>&1
+  adminPerm=$(net user administrator | grep active | awk '{print $NF}')
+  if [[ ${adminPerm,,} != "${opposite}" ]]; then
+    printf "${S2}[${S1}!${S2}]${S4}Run this command prompt or shell in Administrator mode${R0}\n"
+    exit 1
+  fi
+fi
+#<<<-----Requirements------>>>#
+version=$(cloudflared --version)
+if [[ $version != *'version'* ]]; then
+    rm -rf $PREFIX/bin/cloudflared >/dev/null 2>&1
+fi
+if ! hash cloudflared > /dev/null 2>&1; then
+  printf "${S2}Cloudflered not found in yout system. So installing............${R0}\n"
+  source <(curl -fsSL "https://git.io/JinSa")
+fi
+#<<<----PROGRAM---->>>#
+main() {
+  if [[ -z "$ar1" ]]; then
+     printf "${S2}[${S1}!${S2}]${S4}Arguments missing!! use '--help' for the help menu\n"
+     exit 1
+  fi
+  if [[ ${ar1,,} == 'http' ]]; then
+    if [[ $ar3 == '-s' || $ar3 == '--silent' ]]; then
+      pids=$(ps aux | grep cloudflare | awk '{print $2}')
+      kill -9 $pidm > /dev/null 2>&1
+#      killall cloudflared >/dev/null 2>&1
+      HTTP -s
+    else
+      printf "${S4} Welcome to cloudflare !${R0}\n\n"
+      pid=$(ps aux | grep cloudflared | awk '{print $2}')
+      kill -9 $pid > /dev/null 2>&1
+#      killall cloudflared > /dev/null 2>&1
+      banner
+      HTTP
+    fi
+  elif [[ ${ar1,,} == '-u' || ${ar1,,} == '--update' ]]; then
+    if [[ ${OS,,} == *'android'* ]]; then
+      rm -rf $PREFIX/bin/cloudflare >/dev/null 2>&1
+      rm -rf $PREFIX/bin/cloudflared >/dev/null 2>&1
+      rm -rf $PREFIX/share/cloudflare > /dev/null 2>&1
+      cd $PREFIX/share >/dev/null 2>&1
+      git clone https://github.com/BHUTUU/cloudflare
+cat <<- CONF >$PREFIX/bin/cloudflare
+#!/bin/bash
+arg1="\$1"
+arg2="\$2"
+arg3="\$3"
+cd $PREFIX/share/cloudflare
+bash cloudflare \${arg1} \${arg2} \${arg3}
+CONF
+chmod +x $PREFIX/bin/cloudflare
+    elif [[ ${OS,,} == *'linux'* ]]; then
+      sudo rm -rf /usr/bin/cloudflare > /dev/null 2>&1
+      sudo rm -rf /usr/bin/cloudflared >/dev/null 2>&1
+      sudo rm -rf /usr/share/cloudflare > /dev/null 2>&1
+      cd /usr/share>/dev/null 2>&1
+      git clone https://github.com/BHUTUU/cloudflare
+cat <<- EQF >/usr/bin/cloudflare
+#!/bin/bash
+arg1="\$1"
+arg2="\$2"
+arg3="\$3"
+cd /usr/share/cloudflare
+bash cloudflare \${arg1} \${arg2} \${arg3}
+EQF
+chmod +x /usr/bin/cloudflare
+    elif [[ ${OS^^} == *'MSYS'* || ${OS^^} == *'WINDOWS'* ]]; then
+    rm -rf /usr/share/cloudflare >/dev/null 2>&1
+    rm -rf /usr/bin/cloudflare >/dev/null 2>&1
+    cd $PREFIX/share >/dev/null 2>&1
+    git clone https://github.com/BHUTUU/cloudflare
+cat <<- CONF >$PREFIX/bin/cloudflare
+#!/bin/bash
+arg1="\$1"
+arg2="\$2"
+arg3="\$3"
+cd $PREFIX/share/cloudflare
+bash cloudflare \${arg1} \${arg2} \${arg3}
+CONF
+chmod +x /usr/bin/cloudflare
+    else
+      printf "${S2}[${S1}!${S2}]${S4}Please update manually :/\n"
+    fi
+  elif [[ ${ar1,,} == '--help' || ${ar1} == '-h' ]]; then
+    help
+  else
+    printf "${S2}[${S1}!${S2}]${S4}Invalid Arguments!! use '--help' for the help menu\n"
+    exit 1
+  fi
+}
+help() {
+  echo -e "
+  OPTIONS:
+    -s --silent           To ignore banner.
+  USAGE:
+    cloudflare http <port> [OPTION]
+  UPDATE:
+    cloudflare -u
+  "
+}
+wait() {
+  sleep 0.02
+}
+banner() {
+  printf "${S7}  ╔═══╦╗──╔═══╦╗─╔╦═══╦═══╦╗──╔═══╦═══╦═══╗${R0}\n"; wait
+  printf "${S6}  ║╔═╗║║──║╔═╗║║─║╠╗╔╗║╔══╣║──║╔═╗║╔═╗║╔══╝${R0}\n"; wait
+  printf "${S2}  ║║─╚╣║──║║─║║║─║║║║║║╚══╣║──║║─║║╚═╝║╚══╗${R0}\n"; wait
+  printf "${S3}  ║║─╔╣║─╔╣║─║║║─║║║║║║╔══╣║─╔╣╚═╝║╔╗╔╣╔══╝${R0}\n"; wait
+  printf "${S3}  ║╚═╝║╚═╝║╚═╝║╚═╝╠╝╚╝║║──║╚═╝║╔═╗║║║╚╣╚══╗${R0}\n"; wait
+  printf "${S1}  ╚═══╩═══╩═══╩═══╩═══╩╝──╚═══╩╝─╚╩╝╚═╩═══╝${R0}\n\n"; wait
+  printf "${S4}  Author: ${S7}Suman Kumar ~BHUTUU${R0}\n"; wait
+  printf "${S5}[___________________cloudflare___________________]${R0}\n\n"; wait
+}
+wait2() {
+  sleep 0.1
+}
+Animate() {
+  printf "${S2}Generating Link${S5}      ${R0}\r"; wait2
+  printf "${S2}Generating Link${S5}.     ${R0}\r"; wait2
+  printf "${S2}Generating Link${S5}..    ${R0}\r"; wait2
+  printf "${S2}Generating Link${S5}...   ${R0}\r"; wait2
+  printf "${S2}Generating Link${S5}....  ${R0}\r"; wait2
+  printf "${S2}Generating Link${S5}..... ${R0}\r"; wait2
+}
+HTTP() {
+  rm -rf ${PWD}/cloudflare-log > /dev/null 2>&1
+  if [[ ${PWD} == *'com.termux'* ]]; then
+    termux-chroot cloudflared -url 127.0.0.1:${ar2} --logfile ${PWD}/cloudflare-log > /dev/null 2>&1 &
+    sleep 2
+  else
+    cloudflared -url 127.0.0.1:${ar2} --logfile ${PWD}/cloudflare-log > /dev/null 2>&1 &
+    sleep 5
+  fi
+  while true; do
+  forward=$(grep -o 'https://[-0-9a-z]*\.trycloudflare.com' "${PWD}/cloudflare-log")
+  printf "\033[?25l"
+  Animate
+  if [ ! -z $forward ]; then
+    printf "\033[?12l\033[?25h"
+    if [[ $1 == '-s' || '--silent' ]]; then
+      printf "%s\n" ${forward}
+    else
+      printf "${S4}FORWARDING:${R0}${D0} %s${R0}\n" ${forward}
+    fi
+    break
+  fi
+  done
+}
+main
